# Generated by Django 3.1.2 on 2020-10-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='')),
                ('thumbnail', models.FileField(upload_to='')),
                ('views', models.IntegerField()),
            ],
        ),
    ]
