# Generated by Django 3.1.2 on 2020-10-12 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('screens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active_plan', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField()),
                ('plan_type', models.CharField(blank=True, choices=[('M', 'Monthly'), ('N', 'No Active Plans'), ('Y', 'Yearly')], max_length=2, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
