# Generated by Django 3.1.2 on 2020-10-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0005_auto_20201013_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('N', 'No Active Plans'), ('M', 'Monthly'), ('Y', 'Yearly')], max_length=2, null=True),
        ),
    ]
