# Generated by Django 3.1.2 on 2020-10-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0007_auto_20201013_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('Y', 'Yearly'), ('M', 'Monthly'), ('N', 'No Active Plans')], max_length=2, null=True),
        ),
    ]
