# Generated by Django 3.1.2 on 2020-10-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0009_auto_20201013_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('Y', 'Yearly'), ('N', 'No Active Plans'), ('M', 'Monthly')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
