# Generated by Django 3.1.2 on 2020-10-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0013_auto_20201013_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='start_date',
            new_name='plan_buy_date',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('M', 'Monthly'), ('Y', 'Yearly'), ('N', 'No Active Plans')], default='N', max_length=2, null=True),
        ),
    ]
