# Generated by Django 3.1.2 on 2020-10-13 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('screens', '0015_auto_20201013_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='plan_buy_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='plan_type',
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_buy_date', models.DateTimeField(blank=True, null=True)),
                ('plan_type', models.CharField(blank=True, choices=[('M', 'Monthly Plan'), ('H', '6 Months Plan'), ('Y', 'Yearly Plan'), ('N', 'No Active Plans')], default='N', max_length=2, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='screens.plans'),
        ),
    ]
