# Generated by Django 3.1.2 on 2020-10-13 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0016_auto_20201013_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('Y', 'Yearly Plan'), ('H', '6 Months Plan'), ('N', 'No Active Plans'), ('M', 'Monthly Plan')], default='N', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='screens.plans'),
        ),
    ]
