# Generated by Django 3.1.2 on 2020-10-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0017_auto_20201013_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plans',
            name='plan_buy_date',
        ),
        migrations.RemoveField(
            model_name='plans',
            name='user',
        ),
        migrations.AddField(
            model_name='plans',
            name='plan_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan_buy_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plans',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('N', 'No Active Plans'), ('H', '6 Months Plan'), ('M', 'Monthly Plan'), ('Y', 'Yearly Plan')], default='N', max_length=2, null=True),
        ),
    ]
