# Generated by Django 3.1.2 on 2020-10-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0018_auto_20201013_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='plan_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plans',
            name='plan_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plans',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('N', 'No Active Plans'), ('M', 'Monthly Plan'), ('H', '6 Months Plan'), ('Y', 'Yearly Plan')], default='N', max_length=2, null=True),
        ),
    ]
