# Generated by Django 3.1.2 on 2020-10-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0024_auto_20201013_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('M', 'Monthly Plan'), ('N', 'No Active Plans'), ('H', '6 Months Plan'), ('Y', 'Yearly Plan')], default='N', max_length=2, null=True),
        ),
    ]
