# Generated by Django 3.1.2 on 2020-10-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0028_auto_20201015_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('N', 'No Active Plans'), ('M', 'Monthly Plan'), ('Y', 'Yearly Plan'), ('H', '6 Months Plan')], default='N', max_length=2, null=True),
        ),
    ]
