# Generated by Django 3.1.2 on 2020-10-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0030_auto_20201016_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('Y', 'Yearly Plan'), ('H', '6 Months Plan'), ('N', 'No Active Plans'), ('M', 'Monthly Plan')], default='N', max_length=2, null=True),
        ),
    ]
