# Generated by Django 3.1.2 on 2020-10-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0034_auto_20201018_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='plans',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('N', 'No Active Plans'), ('H', '6 Months Plan'), ('Y', 'Yearly Plan'), ('M', 'Monthly Plan')], default='N', max_length=2, null=True),
        ),
    ]
