# Generated by Django 3.1.2 on 2020-11-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0035_auto_20201022_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='prime_show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plans',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('N', 'No Active Plans'), ('H', '6 Months Plan'), ('M', 'Monthly Plan'), ('Y', 'Yearly Plan')], default='N', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='show_media/'),
        ),
    ]
